services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7.2
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
